-- ============================================
-- Seed data for default_themes
-- Ejecutar: npx wrangler d1 execute mi-web-personalizable-db --file=./scripts/seed-default-themes.sql
-- ============================================

-- Tema: Clásico
INSERT OR REPLACE INTO default_themes (id, name, description, preview_image, category, sort_order, config) VALUES
('classic', 'Clásico', 'Estilo tradicional y elegante con tipografía serif. Ideal para negocios, despachos y sitios corporativos.', '/images/themes/classic-preview.png', 'business', 1, '{"primaryColor":"#1e3a5f","secondaryColor":"#3b82f6","accentColor":"#2563eb","bgColor":"#fafaf9","textColor":"#292524","textMutedColor":"#78716c","navbarBg":"#ffffff","navbarText":"#292524","navbarBorder":"#e5e7eb","footerBg":"#1e3a5f","footerText":"#fafaf9","footerLinkOpacity":0.7,"cardBg":"#ffffff","cardBorder":"#e5e7eb","cardRadius":4,"cardShadow":"0 1px 2px rgba(0,0,0,0.05)","sectionAltBg":"#f5f5f4","socialBg":"#f5f5f4","fontFamily":"''Merriweather'', Georgia, serif","fontHeadings":"''Playfair Display'', Georgia, serif","fontSizeBase":17,"fontWeight":"400","lineHeight":1.7,"headingLineHeight":1.3,"h1Size":"2.5rem","h2Size":"2rem","h3Size":"1.25rem","layout":"centered","maxWidth":1100,"sectionGap":64,"containerPadding":24,"borderRadius":4,"heroHeight":"450px","heroAlign":"center","heroOverlayColor":"#000000","heroOverlayOpacity":0.35,"heroTextColor":"#ffffff","heroTitleSize":"3rem","heroTitleWeight":"700","heroSubtitleSize":"1.25rem","heroSubtitleColor":"rgba(255,255,255,0.9)","btnStyle":"filled","btnBorderRadius":4,"btnPaddingX":28,"btnPaddingY":12,"btnTextColor":"#ffffff","btnHoverBg":"rgba(30, 58, 95, 0.08)","linkHoverDecoration":"underline","navbarLinkOpacity":0.8}');

-- Tema: Moderno
INSERT OR REPLACE INTO default_themes (id, name, description, preview_image, category, sort_order, config) VALUES
('modern', 'Moderno', 'Diseño contemporáneo con colores vibrantes. Perfecto para startups, tech y portfolios creativos.', '/images/themes/modern-preview.png', 'general', 2, '{"primaryColor":"#6366f1","secondaryColor":"#8b5cf6","accentColor":"#4f46e5","bgColor":"#ffffff","textColor":"#1a1a2e","textMutedColor":"#6b7280","navbarBg":"#ffffff","navbarText":"#1a1a2e","navbarBorder":"#e5e7eb","footerBg":"#1e1b4b","footerText":"#e0e7ff","footerLinkOpacity":0.7,"cardBg":"#ffffff","cardBorder":"#e5e7eb","cardRadius":12,"cardShadow":"0 1px 3px rgba(0,0,0,0.05)","sectionAltBg":"#f9fafb","socialBg":"#f8fafc","fontFamily":"''Inter'', system-ui, sans-serif","fontHeadings":"''Poppins'', system-ui, sans-serif","fontSizeBase":16,"fontWeight":"400","lineHeight":1.6,"headingLineHeight":1.3,"h1Size":"2.5rem","h2Size":"2rem","h3Size":"1.25rem","layout":"full-width","maxWidth":1200,"sectionGap":80,"containerPadding":24,"borderRadius":8,"heroHeight":"600px","heroAlign":"center","heroOverlayColor":"#000000","heroOverlayOpacity":0.4,"heroTextColor":"#ffffff","heroTitleSize":"3rem","heroTitleWeight":"800","heroSubtitleSize":"1.25rem","heroSubtitleColor":"rgba(255,255,255,0.9)","btnStyle":"filled","btnBorderRadius":8,"btnPaddingX":24,"btnPaddingY":14,"btnTextColor":"#ffffff","btnHoverBg":"rgba(79, 70, 229, 0.08)","linkHoverDecoration":"underline","navbarLinkOpacity":0.8}');

-- Tema: Oscuro
INSERT OR REPLACE INTO default_themes (id, name, description, preview_image, category, sort_order, config) VALUES
('dark', 'Oscuro', 'Tema oscuro moderno con acentos brillantes. Ideal para portfolios, gaming y sitios con personalidad.', '/images/themes/dark-preview.png', 'portfolio', 3, '{"primaryColor":"#818cf8","secondaryColor":"#a78bfa","accentColor":"#6366f1","bgColor":"#0f172a","textColor":"#e2e8f0","textMutedColor":"#94a3b8","navbarBg":"#1e293b","navbarText":"#e2e8f0","navbarBorder":"#334155","footerBg":"#020617","footerText":"#94a3b8","footerLinkOpacity":0.7,"cardBg":"#1e293b","cardBorder":"#334155","cardRadius":12,"cardShadow":"0 4px 6px rgba(0,0,0,0.2)","sectionAltBg":"#0f172a","socialBg":"#1e293b","fontFamily":"''Inter'', system-ui, sans-serif","fontHeadings":"''Montserrat'', system-ui, sans-serif","fontSizeBase":16,"fontWeight":"300","lineHeight":1.7,"headingLineHeight":1.3,"h1Size":"2.5rem","h2Size":"2rem","h3Size":"1.25rem","layout":"centered","maxWidth":1200,"sectionGap":72,"containerPadding":24,"borderRadius":10,"heroHeight":"450px","heroAlign":"center","heroOverlayColor":"#000000","heroOverlayOpacity":0.5,"heroTextColor":"#ffffff","heroTitleSize":"3rem","heroTitleWeight":"700","heroSubtitleSize":"1.25rem","heroSubtitleColor":"rgba(255,255,255,0.85)","btnStyle":"filled","btnBorderRadius":10,"btnPaddingX":28,"btnPaddingY":14,"btnTextColor":"#ffffff","btnHoverBg":"rgba(129, 140, 248, 0.1)","linkHoverDecoration":"underline","navbarLinkOpacity":0.8}');
